### ISSUE TITLE
What version of Infoblox API has this been tested against?

### ISSUE THREAD

**Issue by itewk** [ramrexx/CloudForms_Infoblox#2]
I am just curious about which Infoblox API versions you have tested this with or if you have tested it as part of an automated provisioning workflow.

**Comment by ramrexx** [comment]
I have tested it with provisioning workflows a handful of times with success. As for the version i have tried it against wapi versions 1.4 - 2.x with no issues.

**Comment by itewk** [comment]
Thank you sir.
