### ISSUE TITLE
reuse network-info from infoblox to set vm network configuration

### ISSUE THREAD

**Issue by shs-mdro** [ramrexx/CloudForms_Infoblox#3]
Hi

I'm able to provision vm's with infoblox as the backend. Thank you very much for your efforts and publishing this to the community!

Do you have any idea how to reuse the gained information like ip, subnet mask, gateway and dns-servers according to the infoblox-zone, to be reused in later network configuation of a deployed vm?

Environment is rhel 7.6 @ vmware vsphere 6.7.
Other guides are talking about dummy vmware customization templates and other are using ansible to run network reconfiguraiton inside the vm.

Greetings

Michel

**Comment by shs-mdro** [comment]
update:

i tried to copy your list list_infoblox_networks.rb into a new list_infoblox_domain.rb with this changed content, but i'm not getting far:

if networks_array.blank?
  # get an array of networks from infoblox

  network_search_filter = "network?network_view=#{network_view}"
  # specify fields to return in payload
  return_fields = "&_return_fields=network_view,network,netmask,ipv4addr,extattrs,comment,options"

  networks_array = call_infoblox(:get, "#{network_search_filter}" + "#{return_fields}")
  $evm.log(:info, "Inspecting networks_array: #{networks_array.inspect}")
  
  domain_name = networks_array.dig("options", 0, "domain-name", "value")
  $evm.log(:info, "domain name: #{domain_name}")
  
  sleep 120

  networks_array.each do |net|
    comment = "#{net['comment']}@" if net['comment']
    display_string = "#{comment}#{net['options']},#{net['network_view']}"
    dialog_hash[net['options']] = display_string
  end
end

output of infoblox is as this:

<AEMethod list_infoblox_domain> Inspecting networks_array: [{"_ref"=>"network/ZG5zLm5ldHdvcmskMTAuMC4yMC4wLzI0LzA:10.0.20.0/24/default", "comment"=>"test-netz", "extattrs"=>{}, "ipv4addr"=>"10.0.20.0", "netmask"=>24, "network"=>"10.0.20.0/24", "network_view"=>"default", "options"=>[{"name"=>"dhcp-lease-time", "num"=>51, "use_option"=>false, "value"=>"43200", "vendor_class"=>"DHCP"}]}, {"_ref"=>"network/ZG5zLm5ldHdvcmskMTAuMC4zMC4wLzI0LzA:10.0.30.0/24/default", "comment"=>"zweites test-netz", "extattrs"=>{}, "ipv4addr"=>"10.0.30.0", "netmask"=>24, "network"=>"10.0.30.0/24", "network_view"=>"default", "options"=>[{"name"=>"dhcp-lease-time", "num"=>51, "use_option"=>false, "value"=>"43200", "vendor_class"=>"DHCP"}]}, {"_ref"=>"network/ZG5zLm5ldHdvcmskMTkyLjE2OC4yNTQuMC8yNC8w:192.168.254.0/24/default", "comment"=>"prod netz", "extattrs"=>{}, "ipv4addr"=>"192.168.254.0", "netmask"=>24, "network"=>"192.168.254.0/24", "network_view"=>"default", "options"=>[{"name"=>"broadcast-address", "num"=>28, "use_option"=>true, "value"=>"192.168.254.255", "vendor_class"=>"DHCP"}, {"name"=>"dhcp-lease-time", "num"=>51, "use_option"=>false, "value"=>"43200", "vendor_class"=>"DHCP"}, {"name"=>"domain-name-servers", "num"=>6, "use_option"=>true, "value"=>"192.168.254.10", "vendor_class"=>"DHCP"}, {"name"=>"domain-name", "num"=>15, "use_option"=>true, "value"=>"testlab.local", "vendor_class"=>"DHCP"}, {"name"=>"routers", "num"=>3, "use_option"=>true, "value"=>"192.168.254.1", "vendor_class"=>"DHCP"}]}]

**Comment by ramrexx** [comment]
I am not sure I understand what you are asking. Please elaborate or walk me through what you are trying to accomplish.

**Comment by shs-mdro** [comment]
Hi 

As far as i understand, i have to pass the right variable (infoblox_nic_0_network, infoblox_nic_0_dns_domain) from service dialogs / dropdowns into your scripts to populate the right fields.

infoblox_nic_0_network is dynamically availabe from your list_infoblox_networks.rb. But how do i dynamically load and read-only show (within the service dialog) dns_domain, gateway, dns-servers etc.?

The only way right now i see is by hardwiring through the instance schema, but we have multiple tenants/customer, each with their unique infoblox/network-config.

I tried to copy your list_infoblox_networks.rb into the attached list_infoblox_domain.rb
[list_infoblox_domain.zip](https://github.com/ramrexx/CloudForms_Infoblox/files/3440467/list_infoblox_domain.zip)

 which is able to show me the network options hash of a certain network, but not a key value, let's say from "domain-name".

Do you have any ideas how to solve this?

Greetings

Michel

**Comment by ramrexx** [comment]
Sorry for the delay. Just got back from vacation. I think i understand what you are saying. You are already using list_infoblox_networks as a dynamic dialog and want the list_infoblox_domain to be dynamically chosen based on the network chosen or something to that affect. Is this right?

If so, you would modify list_infoblox_domain.rb to filter the lookup dynamically based on the network currently chosen in the dynamic dialog. Let me know if this helps.

**Comment by shs-mdro** [comment]
Hi Kevin

Yes that's correct and i managed to create a domain-lookup using infoblox's "zone_associations".
I also did it for the gateway and the dns-servers, all information are available like this:

dialog_infoblox_nic_0_dns_domain: testlab.local
dialog_infoblox_nic_0_dns_servers: 192.168.254.10
dialog_infoblox_nic_0_gateway: 192.168.254.1
dialog_infoblox_nic_0_network: 192.168.254.0/24
[automation.log](https://github.com/ramrexx/CloudForms_Infoblox/files/3491329/automation.log)

The problem right now is: How do i use vmware's custom specification to use these values for customizing a new vm and setting these network settings?

Right now my customization spec "rhel7" get's ignored, i tried to set it at vmware_CustomizeRequest.rb with the following code:

prov = $evm.root["miq_provision"]

if prov.source.platform == "linux"
  customization_spec = "rhel7"
elsif prov.source.platform == "windows"
  customization_spec = "Windows-Spec-Name"
end

The spec is being set, but unfortunately nothing happens when the vm gets started, it just grabs a dhcp-address and stays there.

What i've seen with Peter McGowan's object walker is, that sysprep is disabled:

$evm.root['miq_provision'].options[:sysprep_enabled] = ["disabled", "<None>"]   (type: Array)

Is this maybe the cause of the problem and how do i enable it?

Greetings & thank you

Michel

**Comment by ramrexx** [comment]
Hey that is great progress. Have you tried setting the following as well?

prov.set_customization_spec('rhel7', true)

Check out one of my older methods as a reference:
https://github.com/ramrexx/CloudFormsPOC/blob/master/Automate/CloudFormsPOC/Infrastructure/VM/Provisioning/StateMachines/Methods.class/__methods__/vmware_customizerequest.rb

And then there is some examples of how to override custom spec attributes here:
https://github.com/ramrexx/CloudFormsPOC/blob/master/Automate/CloudFormsPOC/Infrastructure/VM/Provisioning/StateMachines/Methods.class/__methods__/vmware_preprovision.rb

**Comment by shs-mdro** [comment]
Hi Kevin

I've got good news, "prov.set_customization_spec('rhel7', true)" is working but it sets the ip from the customization template inside, not the setting i'm evaluating at the end from infoblox.

I tried to use your vmware_preprovision.rb and added my infoblox settings, but it still uses the wrong dummy ip-settings from the vmware specification.
[automation.log](https://github.com/ramrexx/CloudForms_Infoblox/files/3501432/automation.log)

provisioning order:
![grafik](https://user-images.githubusercontent.com/51401910/63022627-a04f2980-bea3-11e9-9e6e-b4c5570db273.png)

a object walker dump is also in the log (see "$evm.root['miq_provision'].options[:ip_addr]" pointing to dummy 1.1.1.1).

Somewhere my settings get overriden or my settings doesn't get applied.

Greetings & thank you for your efforts

Michel

**Comment by ramrexx** [comment]
Hi Michael,
I looked through your automation.log and it looks like at line #2402 - [**undefined local variable or method `final_ip_addr' for main:Object**] tells me that your method is not working.

**Comment by shs-mdro** [comment]
Hi Kevin

I’ve managed to get it working! =)

It didn’t need an extra instance to set the network settings, the vlan was missing and i’ve managed to set it up, that it also gets these info from the infoblox extended attributes.

Right now i have a fully functional and tenant-ready solution to get all infos dynamically from infoblox and also register the vm into red hat satellite (mostyl from Peter McGowan project/ebook).

What would you suggest to do about this?

A pull request of my infoblox-part into your project and the same with the satellite part into Peter’s?
Or a new project/fork referencing into both projects?

Greetings

Michel

**Comment by pemcg** [comment]
Hi Michel

Kevin has shared this with me, and this is really good stuff, it will be very useful to other people I'm sure. Rather than making a PR to an existing project, how about briefly writing up what you've done in a short talk.manageiq.org article, and link to your own new repo with your changes. That would help people realise that your code is really current and works with the latest versions. One of the problems of making PRs back into old projects is it can be slightly ambiguous to other people how current it is.

Many thanks,
pemcg

**Comment by shs-mdro** [comment]
Hi Peter, Hi Kevin

Ok, that sounds good to me. I'll fix the remaining bugs and wrap it all up into an article at manageiq.org.

Keep you updated!

Greetings

Michel
