### ISSUE TITLE
A lot of the links lead to a 404 error

### ISSUE THREAD

**Issue by aroundincircles** [ramrexx/CloudForms_Infoblox#4]
Trying to follow the userguide and it has a bunch of broken links. Can this be fixed? 

Example:
https://github.com/ramrexx/CloudForms_Infoblox/blob/master/documentation/images/vm-createcmdb-button.png

**Comment by ramrexx** [comment]
Unfortunately this repo is something I started 3+ years ago and never finished. This repo is based on Ruby for automate. I think you would have better success using the Ansible Infoblox module in your MIQ Automate method. 

Here are some resources that can help you.
Ansible Infoblox: https://docs.ansible.com/ansible/latest/scenario_guides/guide_infoblox.html
ManageIQ Community: http://talk.manageiq.org/
